version: "3.9"

services:
  app:
    build: .
    container_name: clean_arch
    env_file:
      - .env
    
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_session
    restart: always

volumes:
  postgres_data: