version: "3.9"

services:
  app:
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    ports:
      - "6000:6000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    ports:
      - "5436:5432"

  redis:
    ports:
      - "6379:6379"